version: '2'
services:
  lunchbadger-ui:
    build:
      context: .
      dockerfile: containers/ui/Dockerfile
    ports:
      - 8000:8000
  loopback-workspace:
    image: 410240865662.dkr.ecr.us-west-2.amazonaws.com/lunchbadger-workspace:0.0.1
    ports:
      - 3000:3000
      - 3001:3001
