version: '2'
services:
  lunchbadger-ui:
    build:
      context: .
      dockerfile: containers/ui/Dockerfile
    image: lunchbadger-ui:dev
    ports:
      - 8000:8000
  forecast-api:
    image: lunchbadger/forecast-api:0.0.1
    ports:
      - 3000:3000
