version: '2'
services:
  lunchbadger-ui:
    build:
      context: .
      dockerfile: containers/ui/Dockerfile
    image: lunchbadger-ui:dev
    ports:
      - 8000:8000
  forecast-api:
    image: localhost:5000/forecast-api
    ports:
      - 3000:3000
