version: '2'
services:
  lunchbadger-ui:
    build:
      context: .
      dockerfile: containers/ui/Dockerfile
    image: lunchbadger-ui:dev
    ports:
      - 8000:8000
  loopback-workspace:
    image: lunchbadger/lunchbadger-workspace:0.0.1
    ports:
      - 3000:3000
      - 3001:3001
