version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Connect to our private registry
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awscli
            `aws ecr get-login --region us-west-2 --no-include-email`
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: npm install
      - run: docker-compose up -d

workflows:
  version: 2
  build:
    jobs:
      - test